### ISSUE TITLE
Method to set up a specific path

### ISSUE THREAD

**Issue by i-zaitsev** [applait/finderjs#19]
Is it possible to add a functionality that will allow to preset a specific path into FinderJS view? I mean, suppose we have the following "directory tree" (i.e. object):
```
+ root
     |
     + -- dir1
     + -- dir2
           |
           + -- file.txt
```

Then, we can do something like:
```javascript
var finder = createFinderJS();
finder.navigate('/dir2/file.txt');
```

And FinderJS will navigate to this path like if one do it manually using mouse or keyboard. Or, if it is not planned, could you please give a tip how to introduce this functionality manually?

**Comment by i-zaitsev** [comment]
Oops, wrong repo >_<

Sorry, I was asking about another library.

**Comment by kaustavdm** [comment]
Heh, I guess the name is confusing enough :stuck_out_tongue:
